### ISSUE TITLE
 Vue.js & frameworks use

### ISSUE THREAD

**Issue by hugurp** [internet4000/i4k-image-feed#5]
Now that the application has been accepted by Instagram and that its use is therefore not limited to sandboxed users only, do we need to improve the code weight?

Right now the site of the bundled file is `107kb`.

I think it might be possible to get it down to less than 10% of that, if we use https://preactjs.com/ or https://github.com/choojs/choo.

**Comment by oskarrough** [comment]
Yes! I'd like to help with any/all of them.

- preact
- chooj
- vanilla web component

What are the requirements?

- [ ] web component
- [ ] support `token=""` attribute
- [ ] render markup with images

**Comment by oskarrough** [comment]
I found some good comparisons in https://github.com/shprink/web-components-todo. Every framework has it's own folder and build system that can be copy/pasted to get started.

![](https://user-images.githubusercontent.com/1388706/36589944-426428b0-188d-11e8-8ce1-b0b3f39ca9d9.png)

**Comment by oskarrough** [comment]
Closed by #6
